apiVersion: apps/v1
kind: Deployment
metadata:
  name: BillingAmountView
  labels:
    app: BillingAmountView
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BillingAmountView
  template:
    metadata:
      labels:
        app: BillingAmountView
    spec:
      containers:
        - name: BillingAmountView
          image: username/BillingAmountView:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5